# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19b521593784d8728af9e6c709c97812d50c2261e0d4fc9e270365e20d488986d1f06d0cfec3945379252c98e723a91b3c2c7ff8f20c06e991dadce04b103071

test:
  secret_key_base: 0a15e97700c909c5730fdbb00218a4e62b24f57cd8ced849659b5eb9a92b3dac2ef6a41aa40881f46824491b4cf42a1b03c1ca214d7afde58c3ef928de67ba89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
